[package]
name = "whirlpool-tx-replayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "1.0.107"
flate2 = "1.0.27"
csv = "1.3.0"
base64 = "0.21.4"

mysql = "24.0.0"

# solana-program = "=1.16.16"
# solana-program-test = "=1.16.16"
# spl-token = "3.5.0"
anchor-lang = "0.26.0"
whirlpool_base = { git = "https://github.com/orca-so/whirlpools", package = "whirlpool" }

solana-program = "=1.16.16"
solana-program-test = "=1.16.16"

# skip signature verification
solana-banks-server = { path = "crates/solana-banks-server-for-replay" }
